### ISSUE TITLE
Support for Standard SQL

### ISSUE THREAD

**Issue by dirkjbosman** [tomellingham/automate-bigquery#1]
Hi Tom

Cool scripts, but I see these scripts are mostly for legacy SQL ? Any support for migrating to Standard SQL ?

**Comment by tomellingham** [comment]
Hey - simple, you can set the legacy SQL flag to false: --use_legacy_sql=false

**Comment by tomellingham** [comment]
Added this flag to the scripts and committed to master.

**Comment by dirkjbosman** [comment]
I see In Loop_Through_A_Date_Range.sh that there is a "TABLE_DATE_RANGE". 

"As Standard SQL does not support the TABLE_DATE_RANGE, TABLE_DATE_RANGE_STRICT, or TABLE_QUERY functions"  (https://cloud.google.com/bigquery/docs/reference/standard-sql/migrating-from-legacy-sql). 

I have not ran it yet, but just managed to pick that up while scanning over your code. 

Ps: The alternative to cron, could be Airflow. Keen to work on an airflow tutorial hosted on GCP ? DM at @dirkjobosman Could be interesting !
